### ISSUE TITLE
A small optimization to perform faster

### ISSUE THREAD

**Issue by xpz3** [KeyofBlueS/airgeddon-plugins#1]
Hi
Thanks a lot for the plugin. It really helps people using slow pcs and others who are running airgeddon on mobile phones, tablets etc.
I have a suggestion to improve the current code so they it could perform faster. After all we are targetting slower systems, so the faster the better
In your code on line number 79, instead of parsing the whole language file, you can use an airgeddon built in variable called "lang_association" which has all currently supported languages. If a new language is added, then the variable will get updated too. 
Thanks again

**Comment by KeyofBlueS** [comment]
Thanks for Your suggestion! done it

**Comment by xpz3** [comment]
There's one more thing that i noticed. A small bug.
If you generate the language file removing unneeded languages using the expression, SPANISH|GERMAN|RUSSIAN it could break some strings in the generated language file. For example it will break the following elements

```
arr["ENGLISH",75]="Thanks to the \"Spanish pentesting crew\", to the \"Wifislax Staff\", to the forums people who help me, my collaborators, translators and specially to kcdtv and xtonousou for beta testing and support received"
	arr["SPANISH",75]="Gracias al \"Spanish pentesting crew\", al \"Wifislax Staff\", a la gente de los foros que me ayuda, a mis colaboradores, traductores y en especial a kcdtv y xtonousou por el beta testing y el apoyo recibido"
	arr["FRENCH",75]="Merci au \"Spanish pentesting crew\" , au \"Wifislax Staff\", aux gens des forums qui m'ont aidés, à mes collaborateurs, aux traducteurs et tout spécialement à kcdtv et xtonousou pour les tests en phase bêta et son soutien"
	arr["CATALAN",75]="Agraïments al \"Spanish pentesting crew\", al \"Wifislax Staff\", a la gent dels fòrums que m'ajuda, als meus col·laboradors, traductors i especialment al kcdtv i xtonousou per les proves beta i el suport rebut"
	arr["PORTUGUESE",75]="Agradecimentos a \"Spanish pentesting crew\", \"Wifislax Staff\", as pessoas dos fóruns por me ajudar, os colaboradores, tradutores e especialmente para kcdtv e xtonousou por testes beta e também a todo apoio recebido"
	arr["RUSSIAN",75]="Спасибо \"Spanish pentesting crew\", за \"Wifislax Staff\", людям с форумов, которые мне помогают, тем, кто принимает участие в проекте, переводчикам и особенно kcdtv и xtonousou за бета тестирование и полученную поддержку"
	arr["GREEK",75]="Τις ευχαριστίες μου στην \"Ισπανική ομάδα pentesting\", στο \"Wifislax Staff\", στα άτομα από το forum που με βοηθάνε, στους συνεργάτες μου, στους μεταφραστές και ειδικά στον kcdtv και στον xtonousou για το beta testing και την υποστήριξη που λάβαμε"
	arr["ITALIAN",75]="Grazie alla \"Spanish pentesting crew\", a \"Wifislax Staff\", alla gente dei forum per aiutarmi, al mio staff, ai traduttori e soprattutto a kcdtv e xtonousou per il beta testing e il supporto ricevuto"
	arr["POLISH",75]="Podziękowania dla \"Spanish pentesting crew\", \"Wifislax Staff\", ludziom z forum którzy mi pomagają, moim współpracownikom, tłumaczom, a zwłaszcza kcdtv i xtonousou za testy beta i otrzymane wsparcie"
	arr["GERMAN",75]="Danke an die \"Spanish Pentesting Crew\", an den \"Wifislax Staff\", an die Leute in den Foren, die mir helfen, an meine Mitarbeiter, Übersetzer und besonders an kcdtv und xtonousou für den Beta-Test und die erhaltene Unterstützung"
	arr["TURKISH",75]="Teşekkürler \"Spanish pentesting crew\", to the \"Wifislax Staff\", to the forums people who help me, my collaborators, translators and specially to kcdtv and xtonousou for beta testing and support received"
```
The word spanish is there in all strings. There are more strings like this.
To correct this, you can do a case sensitive search which would resolve the current problems i think. But in future if we add more strings with the language name in the value part, it will be broken again. So you can improve the regex to match only the part in the array key.
Thanks again

**Comment by KeyofBlueS** [comment]
The search is case sensitive yet, is the default in grep. But the code must be improved for sure to match only the part in the array key, just in case some language name in uppercase is present in the value part.

**Comment by xpz3** [comment]
Yea it's case sensitive by default. I forgot that. Yea just improve the regex just in case

**Comment by KeyofBlueS** [comment]
I think the bug is fixed now. Thanks :)

**Comment by xpz3** [comment]
Great!!

**Comment by xpz3** [comment]
(Soon deprecated as slowness will be fixed directly in airgeddon next release).

Regarding this, even though the slowness will be fixed inside airgeddon itself, your plugin is still usable. The plugin reduces the amount of ram used by airgeddon to load all the arrays for all languages. This is good especially with phones tablets mini windows pcs etc

**Comment by KeyofBlueS** [comment]
Good idea

**Comment by xpz3** [comment]
There's a problem thats there from the beginning which went unnoticed. If you are still updating the plugin, there is an array in language file called et_misc_texts which is used to load strings on the different types of captive portal.
Apart from the interface language, there's an additional captive portal language selection choice given to airgeddon users. So if they choose another language there other than interface language, the captive portal will show pages without text as the array is empty.
For example, the attacker prefers interface language as English but he is targeting a greek user and he wants to load the captive portal in greek.
Another case that happened today. A guy wanted to support captive portal page in korean language which we dont have support for. So he replaced all greek strings with korean and selected greek as portal language so that it loads korean. He uses your plugin. So it doesn't work for him too..

Hope you got my point

**Comment by KeyofBlueS** [comment]
Fixed, thanks for reporting

**Comment by KeyofBlueS** [comment]
> (Soon deprecated as slowness will be fixed directly in airgeddon next release).
> 
> Regarding this, even though the slowness will be fixed inside airgeddon itself, your plugin is still usable. The plugin reduces the amount of ram used by airgeddon to load all the arrays for all languages. This is good especially with phones tablets mini windows pcs etc

Dear @xpz3, after some testing I'm not really sure if UI-Boost plugin can really reduce the amount of ram used by airgeddon, as You said. Have You tested it? If yes, how?
Airgeddon's check_language_strings function is done before plugin system start to work and at this point the complete language strings file has already been sourced. Could You confirm this please? Thanks.

In order for UI-Boost plugin to reduce memory usage (considerably it seems, e.g. about 16624K vs 29156K in my tests), I guess some modifications are needed in airgeddon itself, e.g. doing language stuff AFTER plugin system is deployed, but I can do nothing on my side.

If You guys at airgeddon's dev team are concerned about to solve this, let me know. If some modifications will be needed on UI-Boost plugin too, I'll kindly do it. Meanwhile, if You confirm that UI-Boost plugin doesn't actually alter memory usage, I'll set plugin_maximum_ag_affected_version to 10.11, again.

Regards.

**Comment by xpz3** [comment]
The thing is, i wrote a similar plugin a day after you sent it to @Oscar. But at that time i was unaware that you were developing/developed it. So what i did was hook the function that sources the language strings functions and overrides or with the newly generated file. So the actual language file is not sourced at all. And for this i changed the plugin parsing function call to be called after parsing the plugins which should be done from airgeddon main function. In your case the plugins are parsed later since there's no change in main function. 
Regarding the memory saving i forgot that we both did the plugin in different ways, my bad.

**Comment by KeyofBlueS** [comment]
Ok it's more clear now, thanks @xpz3.
With this commit https://github.com/KeyofBlueS/airgeddon/commit/7202b1e38ddac480de595cdee1bac13e08883713, plugin system is deployed earlier. If it's ok for You @OscarAkaElvis, I could make a pull request. If this commit will be merged, UI-Boost (as some other plugins) must be updated in order to correctly work, and obviously plugin_minimum_ag_affected_version must be updated too.
Please let me know if I should continue to take care about this or if I should throw it in the trash.

Regards

**Comment by OscarAkaElvis** [comment]
are you talking about PR to main airgeddon repo??

**Comment by OscarAkaElvis** [comment]
I don't like to change stuff in main airgeddon repo... and for what? for this plugin? the plugin was nice but after v9.20 is pointless due the improvement done in airgeddon. I think I'm not going to modify something as important as the order of the first initializations to improve something that is not needed anymore, sorry. In addition I must say that to change order of the initializations could have unpredictable behaviors on other stuff (plugins, etc).

**Comment by OscarAkaElvis** [comment]
maybe i'm understanding something... 🙄   please explain to me the reason for the PR. The improvement we did in main repo is even faster than plugin. The plugin given to us the idea to improve, that's true. But I can't see how the speed can be improved further.

**Comment by KeyofBlueS** [comment]
@OscarAkaElvis we aren't talking about speeding up the user interface anymore, but about considerably lowering memory usage instead, as our friend @xpz3 pointed out, this is useful in devices with limited ram memory e.g smartphones, tablets ecc...

**Comment by KeyofBlueS** [comment]
The purpose of this PR is to deploy plugin system before setting language strings, in order to make plugins take actions (override, prehook and posthook) a little bit earlier.

UI-Boost in particular could prevent sourcing of big language_strings.sh file, using a specific generated language file (e.g. language_strings_ENGLISH.sh) instead. The advantages of using this approach is airgeddon will use a lower amount of ram memory, this is useful in devices with limited ram memory e.g smartphones, tablets and so on

**Comment by OscarAkaElvis** [comment]
This is something that I must check carefully. I need to do some tests with other plugins and other stuff. I'll need some time to evaluate it.

**Comment by KeyofBlueS** [comment]
For sure some of my plugins must be updated after this change, but it's really not an hard task.
If you think it's worth it, go ahead.
And thanks for your interest.

**Comment by OscarAkaElvis** [comment]
Hi. I was testing this deeply. Sorry but it seems it doesn't worth to do this change.

![image](https://user-images.githubusercontent.com/5803348/83381902-2a8c5e00-a3e2-11ea-9416-f222b5d507da.png)

Upper windows (airgeddon an htop) are airgeddon as normal (airgeddon PID 3376). Lower windows are from airgeddon with your changes (airgeddon PID 3599). No difference about % consumed RAM. There is hardly any difference. I prefer to have centralized the calls to the strings initialization for now.

**Comment by KeyofBlueS** [comment]
Have You tried with no plugin right? If yes, that's normal. Anyway try it with this https://raw.githubusercontent.com/KeyofBlueS/airgeddon-plugins/Dev/ui_boost.sh (the plugin it's not fully functional as it is right now, but can give You the idea of how it can reduce memory usage)

**Comment by KeyofBlueS** [comment]
Ok @OscarAkaElvis, I tested it for You
![airgeddon_2020-06-05_17-14-23](https://user-images.githubusercontent.com/45725677/83893758-a4a94380-a750-11ea-862e-191e44fbac7e.png)
Upper-left window is airgeddon as normal (airgeddon PID 832966). Lower-left window is from airgeddon with my changes and ui-boost plugin as linked in above message (airgeddon PID 833288).
As You can see in Right window is htop showing both airgeddon processes: modified airgeddon with ui-boost plugin (airgeddon PID 833288) has less than half consumed RAM compared to airgeddon as normal (airgeddon PID 832966).

**Comment by OscarAkaElvis** [comment]
That means that the difference will be only if we add plugins? Why is not affecting to the already one existing plugin? maybe because the missing dependencies plugin is almost costless. So it affects only in case of using big or "heavy" plugins. In that case not sure if it worths.

Let me discuss this internally with one of the plugins system creator. But I can tell you that we try to have as less calls to that functions as possible... that is the main reason of not adding this instantly.

**Comment by KeyofBlueS** [comment]
No @OscarAkaElvis, plugins size doesn't matter xd

As mentioned some posts above:
> The purpose of this PR is to deploy plugin system before setting language strings, in order to make plugins take actions (override, prehook and posthook) a little bit earlier.
> 
> UI-Boost in particular could prevent sourcing of big language_strings.sh file, using a specific generated language file (e.g. language_strings_ENGLISH.sh) instead. The advantages of using this approach is airgeddon will use a lower amount of ram memory, this is useful in devices with limited ram memory e.g smartphones, tablets and so on

So, airgeddon as normal:
start airgeddon -> airgeddon will source (big original) language strings file (language_strings.sh) = more RAM usage

modified airgeddon with ui-boost plugin:
start airgeddon -> ui-boost plugin will make a specific language file -> airgeddon will source small language strings file (e.g. language_strings_ENGLISH.sh) = less RAM usage

made myself clear?

Anyway thanks for Your effort in following this issue.

**Comment by OscarAkaElvis** [comment]
Finally I think this changes doesn't worth. Sorry. Very few memory for very few devices. Because any device even old phones have a lot of memory to run this as is.

**Comment by KeyofBlueS** [comment]
ok got it
