### ISSUE TITLE
regdomain - Restore regulatory domain upon exit airgeddon

### ISSUE THREAD

**Issue by KeyofBlueS** [KeyofBlueS/airgeddon-plugins#12]
As of now, upon exit airgeddon, the regulatory domain is the one set by regdomain plugin.

With this commit https://github.com/KeyofBlueS/airgeddon-plugins/commit/8e64d78d63aa5f63fa640762b03d1ebf678fa208 wi will prehook exit_script_option and hardcore_exit in order to restore regulatory domain upon exit airgeddon.

restore_regulatory_domain must be set to 'true' in the 'USER CONFIG SECTION' of regdomain plugin.

Anyone willing to test it?
@Bogdan107

**Comment by Bogdan107** [comment]
Worked!

**Comment by KeyofBlueS** [comment]
Fine, thanks @Bogdan107
