### ISSUE TITLE
captured_handshakes breaks the password check 

### ISSUE THREAD

**Issue by minanagehsalalma** [KeyofBlueS/airgeddon-plugins#14]
I am using it on Version 10.42

after providing the handshake files to the `plugins/captured_handshakes/` folder

After the fake AP starts , and then entering a password the webserver window says that it can't find the handshake file even tho we have already selected it from the available handshakes file shown to us be the plugin

**Comment by KeyofBlueS** [comment]
I've just tried and it works as expected here, sorry.
