### ISSUE TITLE
Can the sort_targets plugin get a sort by clients number option ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [KeyofBlueS/airgeddon-plugins#16]
It would be really useful to know which network has the most clients so to know which would be a more potential target 

![image](https://user-images.githubusercontent.com/20546638/149230966-2c208501-06c3-4e30-9049-9d0c5aeda4ae.png)

thanks

**Comment by KeyofBlueS** [comment]
Don't think so because there is no such value in airgeddon output

**Comment by minanagehsalalma** [comment]
> Don't think so because there is no such value in airgeddon output

@KeyofBlueS wifiphisher has the method to grab clients numbers

I think it can be added to airegeddon using a prehook

But otherwise  i agree .

**Comment by KeyofBlueS** [comment]
How about this? https://github.com/KeyofBlueS/airgeddon-plugins/commit/dac282c217fc80751500c23a1c3d40703f55d169 :smile:

**Comment by minanagehsalalma** [comment]
> How about this? [dac282c](https://github.com/KeyofBlueS/airgeddon-plugins/commit/dac282c217fc80751500c23a1c3d40703f55d169) 😄

@KeyofBlueS whoa man you rock , that works really really well 

That so awesome , but i have one tiny problem , the cli short name seems like command line not clients tho 😥
![Capture](https://user-images.githubusercontent.com/20546638/149599836-6e823d91-48ee-4882-9041-ed88e777abc5.png)

**Comment by minanagehsalalma** [comment]
look like you are up to adding great ideas 

check these 
[wifiphisher pulls](https://github.com/wifiphisher/wifiphisher/pulls)

and [i have created a list before about possible ideas for an evil twin attack 
that haven't been added before](https://github.com/soyalk/probalk/issues/2) 

One of them i like the most is a mimic of WIFI network manager based on the useragent of the device

**Comment by KeyofBlueS** [comment]
Yes I know how it looks like, I've write it :) I think is fine, it's not important and from the context we understand the true meaning.

For the rest... yeah... maybe I'll take a look at it... but that isn't material for an issue here
