### ISSUE TITLE
Captured_handshakes.sh "Failed to open, no such file or directory" after clicking "send" on captive portal.

### ISSUE THREAD

**Issue by nullvoid413** [KeyofBlueS/airgeddon-plugins#18]
#### What is your plugin?

Captured_handshakes.sh

#### What is your airgeddon version?

V11.11

#### What is the expected behavior?

Whenever I open the captive portal and click "send" button to send the password, it appears in yellow on the web server window the following:
Failed to open /plugins/captured_handshakes/handshake-xx:xx:xx.cap' (2): No such file or directory 

#### Describe the issue and the steps to reproduce it

https://i.ibb.co/xFQM7Ng/IMG-6012.jpg

1. The handshake is captured
2. I save to the default folder (click enter)
3. The attack start AP + Captive Portal
4. Whenever I enter the password on Captive Portal and click "send" button to send the password, it shows me that error "Failed to open /plugins/captured_handshakes/handshake-xx:xx:xx.cap' (2): No such file or directory"

It's always when I click the send button. And in the other hand, there's no password showing and no password saved to the output folder.

**Comment by ZeroChaos-** [comment]
I have a sneaking suspicion it's related to https://github.com/v1s1t0r1sh3r3/airgeddon/blob/master/airgeddon.sh#L14124-L14138

**Comment by KeyofBlueS** [comment]
Hi @nullvoid413 . I cannot reproduce this, i'm really sorry.
As @ZeroChaos- pointed out, that function in airgeddon could be the culprit of your issue. Could you tell me the full path in which airgeddon.sh is?

You could try to set the full path of the `captured_handshakes` folder under the `USER CONFIG SECTION` of the plugin. Let me know if this is working for you.

**Comment by nullvoid413** [comment]
Closed.
It is an Airgeddon bug that as been here for years and nobody noticed.
Already escalated this issue to Airgeddon's developers.

Sorry for the inconvenience.
