### ISSUE TITLE
Captive portal not showing/working

### ISSUE THREAD

**Issue by MikzG** [KeyofBlueS/airgeddon-plugins#5]
So when I installed airgeddon the evil twin attack with captive portal was working but after I installed some plugins it doesnt show when I launch the attack like it connects to the fake network but the captive portal doesnt show!
I already tried to reinstall airgeddon without the plugins

**Comment by KeyofBlueS** [comment]
Hi @MikzG, fill the issue template please.

```
#### What is your plugin?

<!--- Insert answer here -->

#### What is your plugin version?

<!--- Insert answer here -->

#### What is your airgeddon version?

<!--- Insert answer here -->

#### What is the expected behavior?

<!--- Insert answer here -->

#### Describe the issue and the steps to reproduce it

<!--- Insert description here. Screenshots or any clarifying info are welcome too -->

```

**Comment by KeyofBlueS** [comment]
Closed due to inactivity
