### ISSUE TITLE
Custom portal not starting up 

### ISSUE THREAD

**Issue by genusmig** [KeyofBlueS/airgeddon-plugins#8]
#### What is your plugin?

Custom Portal

#### What is your plugin version?

0.1.6

#### What is your airgeddon version?

10.41

#### What is the expected behavior?

Custom portal not starting

#### Describe the issue and the steps to reproduce it

Unable to load the custom made portal
Please help to check the code I have uploaded.
[final.html.txt](https://github.com/KeyofBlueS/airgeddon-plugins/files/6448795/final.html.txt)
[portal.css.txt](https://github.com/KeyofBlueS/airgeddon-plugins/files/6448801/portal.css.txt)

**Comment by genusmig** [comment]
I'll close this case. xpz3 help me to fix it.

**Comment by KeyofBlueS** [comment]
This not seems plugin related, sorry.
